# Generated by Django 5.0.13 on 2025-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0007_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='Count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thứ tự kênh'),
        ),
    ]
