# Generated by Django 5.0.13 on 2025-09-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0008_channel_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Avatar_Product')),
                ('Video', models.FileField(blank=True, null=True, upload_to='Video_Product')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Video',
                'ordering': ['id'],
            },
        ),
    ]
