# Generated by Django 5.0.13 on 2025-09-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0009_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Danh mục'),
        ),
    ]
