# Generated by Django 5.0.13 on 2025-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0010_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Video_Daga'),
        ),
        migrations.AlterField(
            model_name='video',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='Video_Daga'),
        ),
    ]
