# Generated by Django 5.0.13 on 2025-10-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0011_alter_video_avatar_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='Banner',
            field=models.ImageField(blank=True, null=True, upload_to='ADS_Daga'),
        ),
        migrations.AddField(
            model_name='ads',
            name='Link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link quảng cáo'),
        ),
    ]
