# Generated by Django 5.0.13 on 2025-10-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0012_ads_banner_ads_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên kênh'),
        ),
    ]
