# Generated by Django 5.0.13 on 2025-10-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0013_ads_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='Name',
        ),
        migrations.AddField(
            model_name='ads',
            name='Note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ghi chú quảng cáo'),
        ),
    ]
