# Generated by Django 5.0.13 on 2025-10-23 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0014_remove_ads_name_ads_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Danh mục')),
                ('Describe', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Mô tả')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Video',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Odds_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Odds_Image')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Link_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sleekweb.odds')),
            ],
            options={
                'verbose_name_plural': 'Video',
                'ordering': ['id'],
            },
        ),
    ]
