# Generated by Django 5.0.13 on 2025-11-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0015_odds_odds_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='odds',
            name='Count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thứ tự kênh'),
        ),
        migrations.AlterField(
            model_name='odds_image',
            name='Link_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sleekweb.odds'),
        ),
    ]
