# Generated by Django 5.0.13 on 2025-11-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0016_odds_count_alter_odds_image_link_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Odds_Image')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Ảnh động',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='odds',
            options={'ordering': ['id'], 'verbose_name_plural': 'Tỉ lệ cược'},
        ),
        migrations.AlterModelOptions(
            name='odds_image',
            options={'ordering': ['id'], 'verbose_name_plural': 'Ảnh tỉ lệ cược'},
        ),
    ]
