# Generated by Django 5.0.13 on 2025-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0017_animation_image_alter_odds_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation_image',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Animation_Image'),
        ),
    ]
