# Generated by Django 5.0.13 on 2025-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0018_alter_animation_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Channel_Daga'),
        ),
    ]
