# Generated by Django 5.0.13 on 2025-12-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0019_channel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mật khẩu'),
        ),
    ]
