# Generated by Django 5.2.7 on 2026-01-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0020_channel_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="Key",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Key live"
            ),
        ),
    ]
