# Generated by Django 5.2.7 on 2026-01-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0021_alter_channel_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="Iframe",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Key live"
            ),
        ),
    ]
