# Generated by Django 5.2.7 on 2026-01-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0022_channel_iframe"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="StreamType",
            field=models.CharField(
                blank=True,
                choices=[("url", "URL phát (HLS/M3U8)"), ("iframe", "IFrame embed")],
                default="url",
                max_length=10,
                null=True,
                verbose_name="Loại phát",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="Iframe",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="Iframe embed"
            ),
        ),
    ]
