# Generated by Django 5.2.7 on 2026-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0023_channel_streamtype_alter_channel_iframe"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="Time",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ngày"
            ),
        ),
    ]
